version: "3.8"

services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: auth-service
    ports:
      - "8081:8080"
    volumes:
      - ./services/auth/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
